version: 2
jobs:
 build:
   machine: true
   steps:
     - run:
         command: |
           if [[ ${CIRCLE_SHELL_ENV} =~ "localbuild" ]]; then
             mkdir -p /tmp/_circleci_local_build_repo
           fi

     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI

     - run :
        name: Build Image
        command: docker run -it --rm --network host -v "$(PWD)/tests:/tests" -v /var/run/docker.sock:/var/run/docker.sock docker_sql_transfer:dev-test bash
