version: 2
jobs:
  build:
    machine:
      image: jpetazzo/dind
      docker_layer_caching: true
    steps:
      - run: apt-get update && apt-get install -y git

      - checkout

      - run:
          name: 'Build Image'
          command: docker build -t docker_sql_transfer:dev . && docker build -f DockerfileTest --rm -t docker_sql_transfer:dev-test .

      - run:
          name: "Pull images for test script"
          command: docker pull postgres:12 && docker pull mcr.microsoft.com/mssql/server:2017-latest

      - run:
          name: 'Test'
          command: bash -e test.sh
